### PR TITLE
fix bug with metacal psf method "gauss"

### PR DESCRIPTION
**Pull request by esheldon**
The psf determination was being done on the pre pixel rather than post pixel psf.  This required a Convolve with the pixel afterward, which does not work as expected when the wcs is complex

Added a metacal accuracy test as well

### CODE REVIEW

**Comment by esheldon** [comment]
@beckermr is that failure obvious to you?

**Comment by beckermr** [comment]
I'll check the test thing in a bit. I still don't get why this fails or what is going on.

**Comment by esheldon** [comment]
Looks like the column `det_bands` was not expected

**Review by beckermr — CHANGES_REQUESTED** [review]
So I am looking at this in detail and this code is wrong IMHO. IDK why it works, but it is not logically consistent. 

The function _get_gauss_target_psf returns a `galsim.Gaussian` object. Then `do_dilate` applies a dilation based on the shear. Finally, the output of `_get_dilated_psf` is used in this block of code

```python
        if key not in self._psf_cache:
            psf_grown = self._get_dilated_psf(shear, doshear=doshear)

            # this should carry over the wcs
            psf_grown_image = self.psf_image.copy()

            try:
                psf_grown.drawImage(
                    image=psf_grown_image,
                    method='no_pixel',  # pixel is already in psf
                )
            except RuntimeError as err:
                # argh, galsim uses generic exceptions
                raise GMixRangeError("galsim error: '%s'" % str(err))

            self._psf_cache[key] = (psf_grown_image, psf_grown)
```

Notice here the image is rendered with `no_pixel`. However, with the changes above, the pixel was never added back in. It doesn't matter that you kept the pixel when calling `_get_gauss_target_psf` since this function simply returns a raw galsim object that knows nothing of the pixel.

What I think is happening is that indeed the pixel handling has gone wrong and the change here happens to make things just right for the test case.

**Comment by esheldon** [comment]
With the new code the pixel is never taken out

**Comment by esheldon** [comment]
There was never a reason to take out the pixel before running that algorithm.  In fact I think it was a bad idea to do so because the determination of the gaussian was affected by noise amplification.

**Comment by beckermr** [comment]
Sure but you do have to add the pixel back in in order for the rendering to be correct with `no_pixel`.

**Comment by beckermr** [comment]
Not taking it out doesn't matter. The returned reconv PSF is not an interpolated image. It is a Gaussian from galsim.

**Comment by esheldon** [comment]
This is the same thing we do with fitgauss.  In that case we fit the pixelized PSF, dilate it and render with no pixel.

It is true that there could be problems with an undersampled PSF, but that's not unique to this method.

**Comment by esheldon** [comment]
Right, when I said the pixel is in it I meant that it is broader than the pixelized PSF we started with, so should be valid.

But its not correct that the algorithm is just returning a too small PSF.  Any time I reconvolve by the pixel I'm getting a bias.

For example I can just pick some good PSF by hand, say the one returned by fitgauss.  If I convolve that by the pixel and use it I get a bias.  This is what is going wrong.

**Comment by beckermr** [comment]
Ahhhhhh. With a WCS that is not diagonal, the pixel is asymmetric. It also not true that the pixel is symmetric even with a diagonal WCS. I am betting we have an additive effect that looks like a multiplicative one.

**Pull request merged**
