### PR TITLE
Prep for release of 2.0

### PR DESCRIPTION
**Pull request by esheldon**
removed use of 2to3, and future imports

mostly formatting with black followed by flake8

### CODE REVIEW

**Comment by esheldon** [comment]
TODO

- [ ] rework or remove most of the bootstrappers
- [ ] remove unused code that probably doesn't even work, e.g. importance samplers, etc.
- [ ] dramatically imporove test coverage
- [ ] add pixel level tests for metacal operations

**Comment by beckermr** [comment]
You may want more than one pr for this list. It is pretty big.

**Comment by esheldon** [comment]
Well, I didn't  want this stuff in master until 2.0 is released.  But you are right this is big stuff. Maybe we could do PRs against this branch

**Comment by beckermr** [comment]
You might consider making a 1.X branch that only gets patch version updates.

**Comment by beckermr** [comment]
Though I hate that personally since backporting stuff is annoying.

**Comment by esheldon** [comment]
Unless there are objections, I'm going to merge this one and do some other PRs towards v2

**Comment by beckermr** [comment]
Sure. I have it on my plate to do some of this work as part of my pipeline scientist time as well.

**Comment by esheldon** [comment]
sounds good

**Pull request merged**
